name: monsoon-kernels
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - adlfs
  - basemap
  - bottleneck
  - cartopy
  - dask
  - fsspec
  - gcsfs
  - h5py
  - h5netcdf
  - ipykernel
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - planetary-computer
  - proplot
  - pystac-client
  - pytorch
  - wandb
  - xarray
  - xesmf
  - zarr
